/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : IO
 #	author : miyako
 #	2017/05/22
 #
 # --------------------------------------------------------------------------------*/



// --- Stream I/O
void fopen(sLONG_PTR *pResult, PackagePtr pParams);
void fclose(sLONG_PTR *pResult, PackagePtr pParams);
void fwrite(sLONG_PTR *pResult, PackagePtr pParams);
void fread(sLONG_PTR *pResult, PackagePtr pParams);
void fgetpos(sLONG_PTR *pResult, PackagePtr pParams);
void fsetpos(sLONG_PTR *pResult, PackagePtr pParams);
