/* --------------------------------------------------------------------------------
 #
 #    4DPlugin.cpp
 #    source generated by 4D Plugin Wizard
 #    Project : IO
 #    author : miyako
 #    2017/05/22
 #
 # --------------------------------------------------------------------------------*/

#include "4DPluginAPI.h"
#include "4DPlugin.h"
#include <mutex>
#include <vector>
#include <sys/stat.h>

#pragma mark Context

std::map<uint32_t, FILE*> fopen_contexts;
std::mutex fopen_contexts_mutex;

uint32_t fopen_context_add(FILE *file)
{
    if(file)
    {
        std::lock_guard<std::mutex> lock(fopen_contexts_mutex);
        static uint32_t next_id = 1;
        uint32_t id = next_id++;
        fopen_contexts.insert(std::map<uint32_t, FILE*>::value_type(id, file));
        return id;
    }
    return 0;
}

FILE *fopen_context_get(uint32_t i)
{
    std::lock_guard<std::mutex> lock(fopen_contexts_mutex);
    std::map<uint32_t, FILE*>::iterator pos = fopen_contexts.find(i);
    return (pos != fopen_contexts.end()) ? pos->second : NULL;
}

void fopen_context_remove(uint32_t i)
{
    std::lock_guard<std::mutex> lock(fopen_contexts_mutex);
    std::map<uint32_t, FILE*>::iterator pos = fopen_contexts.find(i);
    if(pos != fopen_contexts.end())
    {
        FILE *file = pos->second;
        fclose(file);
        fopen_contexts.erase(pos);
    }
}

#pragma mark Startup / Exit

bool IsProcessOnExit()
{
    C_TEXT name;
    PA_long32 state, time;
    PA_GetProcessInfo(PA_GetCurrentProcessNumber(), name, &state, &time);
    CUTF16String procName(name.getUTF16StringPtr());
    CUTF16String exitProcName((PA_Unichar *)"$\x0x\x0x\x0\x0\x0");
    return (!procName.compare(exitProcName));
}

void OnExit()
{
    std::lock_guard<std::mutex> lock(fopen_contexts_mutex);
    for(std::map<uint32_t, FILE*>::iterator i = fopen_contexts.begin(); i != fopen_contexts.end(); i++)
    {
        FILE *file = i->second;
        fclose(file);
    }
    fopen_contexts.clear();
}

void OnCloseProcess()
{
    if(IsProcessOnExit())
    {
        OnExit();
    }
}

void OnStartup()
{
    // No action needed on startup
}

#pragma mark -

void PluginMain(PA_long32 selector, PA_PluginParameters params)
{
    try
    {
        PA_long32 pProcNum = selector;
        sLONG_PTR *pResult = (sLONG_PTR *)params->fResult;
        PackagePtr pParams = (PackagePtr)params->fParameters;

        switch(pProcNum)
        {
            case 1:
                fopen(pResult, pParams);
                break;
            case 2:
                fclose(pResult, pParams);
                break;
            case 3:
                fwrite(pResult, pParams);
                break;
            case 4:
                fread(pResult, pParams);
                break;
            case 5:
                fgetpos(pResult, pParams);
                break;
            case 6:
                fsetpos(pResult, pParams);
                break;
        }
    }
    catch(...)
    {
        // Handle exceptions if any
    }
}

void fopen(sLONG_PTR *pResult, PackagePtr pParams)
{
    C_TEXT Param1;
    C_TEXT Param2;
    C_LONGINT returnValue;

    Param1.fromParamAtIndex(pParams, 1);
    Param2.fromParamAtIndex(pParams, 2);

    // Validate path and mode
    if(Param1.getUTF16StringPtr() == NULL || Param2.getUTF16StringPtr() == NULL)
    {
        returnValue.setIntValue(0); // Error: Invalid input
        returnValue.setReturn(pResult);
        return;
    }

    // Convert path/mode to char* (simplified example)
    // Replace with actual conversion logic
    std::string path = "path"; // Placeholder
    std::string mode = "mode"; // Placeholder

    FILE *file = ::fopen(path.c_str(), mode.c_str());
    if(file == NULL)
    {
        returnValue.setIntValue(0); // Error: fopen failed
        returnValue.setReturn(pResult);
        return;
    }

    uint32_t id = fopen_context_add(file);
    returnValue.setIntValue(id);
    returnValue.setReturn(pResult);
}

void fclose(sLONG_PTR *pResult, PackagePtr pParams)
{
    C_LONGINT Param1;
    C_LONGINT returnValue;

    Param1.fromParamAtIndex(pParams, 1);
    uint32_t fileID = Param1.getIntValue();

    fopen_context_remove(fileID);
    returnValue.setIntValue(0);
    returnValue.setReturn(pResult);
}

void fwrite(sLONG_PTR *pResult, PackagePtr pParams)
{
    C_LONGINT Param1;
    C_BLOB Param2;
    C_LONGINT returnValue;

    Param1.fromParamAtIndex(pParams, 1);
    Param2.fromParamAtIndex(pParams, 2);

    FILE *f = fopen_context_get(Param1.getIntValue());
    if(f == NULL)
    {
        returnValue.setIntValue(-1); // Error: Invalid file ID
        returnValue.setReturn(pResult);
        return;
    }

    size_t bytesToWrite = Param2.getBytesLength();
    const uint8_t *data = Param2.getBytesPtr();
    size_t bytesWritten = fwrite(data, sizeof(uint8_t), bytesToWrite, f);

    if(bytesWritten != bytesToWrite)
    {
        returnValue.setIntValue(-1); // Error: fwrite failed
        returnValue.setReturn(pResult);
        return;
    }

    returnValue.setIntValue(bytesWritten);
    returnValue.setReturn(pResult);
}

void fread(sLONG_PTR *pResult, PackagePtr pParams)
{
    C_LONGINT Param1;
    C_BLOB Param2;
    C_LONGINT Param3;
    C_LONGINT returnValue;

    Param1.fromParamAtIndex(pParams, 1);
    Param3.fromParamAtIndex(pParams, 3);

    FILE *f = fopen_context_get(Param1.getIntValue());
    if(f == NULL)
    {
        returnValue.setIntValue(-1); // Error: Invalid file ID
        returnValue.setReturn(pResult);
        return;
    }

    // Get file size if length is not provided
    long cur = ftell(f);
    if(fseek(f, 0, SEEK_END) != 0)
    {
        returnValue.setIntValue(-1); // Error: fseek failed
        returnValue.setReturn(pResult);
        return;
    }
    long end = ftell(f);
    if(fseek(f, cur, SEEK_SET) != 0)
    {
        returnValue.setIntValue(-1); // Error: fseek failed
        returnValue.setReturn(pResult);
        return;
    }

    size_t size = (Param3.getIntValue() > 0) ? Param3.getIntValue() : end - cur;

    if(size > 0)
    {
        std::vector<uint8_t> buf(size);
        size_t bytesRead = fread(&buf[0], sizeof(uint8_t), size, f);
        if(bytesRead != size && !feof(f))
        {
            returnValue.setIntValue(-1); // Error: fread failed
            returnValue.setReturn(pResult);
            return;
        }
        Param2.setBytes(&buf[0], bytesRead);
        returnValue.setIntValue(bytesRead);
    }
    else
    {
        returnValue.setIntValue(0); // No data read
    }

    Param2.toParamAtIndex(pParams, 2);
    returnValue.setReturn(pResult);
}

void fgetpos(sLONG_PTR *pResult, PackagePtr pParams)
{
    C_LONGINT Param1;
    C_LONGINT Param2;
    C_LONGINT returnValue;

    Param1.fromParamAtIndex(pParams, 1);

    FILE *f = fopen_context_get(Param1.getIntValue());
    if(f == NULL)
    {
        returnValue.setIntValue(-1); // Error: Invalid file ID
        returnValue.setReturn(pResult);
        return;
    }

    fpos_t pos = 0;
    returnValue.setIntValue(fgetpos(f, &pos));
    Param2.setIntValue((PA_long32)pos);

    Param2.toParamAtIndex(pParams, 2);
    returnValue.setReturn(pResult);
}

void fsetpos(sLONG_PTR *pResult, PackagePtr pParams)
{
    C_LONGINT Param1;
    C_LONGINT Param2;
    C_LONGINT returnValue;

    Param1.fromParamAtIndex(pParams, 1);
    Param2.fromParamAtIndex(pParams, 2);

    FILE *f = fopen_context_get(Param1.getIntValue());
    if(f == NULL)
    {
        returnValue.setIntValue(-1); // Error: Invalid file ID
        returnValue.setReturn(pResult);
        return;
    }

    // Get file size for bounds checking
    if(fseek(f, 0, SEEK_END) != 0)
    {
        returnValue.setIntValue(-1); // Error: fseek failed
        returnValue.setReturn(pResult);
        return;
    }
    long fileSize = ftell(f);
    if(fseek(f, 0, SEEK_SET) != 0)
    {
        returnValue.setIntValue(-1); // Error: fseek failed
        returnValue.setReturn(pResult);
        return;
    }

    fpos_t pos = Param2.getIntValue();
    if(pos < 0 || pos > fileSize)
    {
        returnValue.setIntValue(-1); // Error: Invalid position
        returnValue.setReturn(pResult);
        return;
    }

    returnValue.setIntValue(fsetpos(f, &pos));
    returnValue.setReturn(pResult);
}
